version: '3.1'
networks:
  api-server:
    driver: bridge
services:
  mongo-moka:
    build: dockers/mongodb
    container_name: mongo-moka
    hostname: mongo-moka
    networks:
      - api-server
    ports:
      - 27017:27017
    volumes:
      - 'mongo-db:/data/db'
      - 'mongo-configdb:/data/configdb'

  redis-moka:
    build: dockers/redis
    container_name: redis-moka
    hostname: redis-moka
    networks:
      - api-server
    ports:
      - 6379:6379
    volumes:
      - 'redis-data:/data'

  mysql-moka:
    build: dockers/mysql
    container_name: mysql-moka
    hostname: mysql-moka
    networks:
      - api-server
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - '3306:3306'

  server-moka:
    build: server
    networks:
      - api-server
    ports:
      - 3000:3000
    depends_on:
      - mysql-moka
      - redis-moka
      - mongo-moka
    # external_links:
    #   - mongo-moka:mongo-moka
    #   - redis-moka:redis-moka
    #   - mysql-moka:mysql-moka
    links:
      - mongo-moka:mongo-moka
      - redis-moka:redis-moka
      - mysql-moka:mysql-moka

volumes:
  mongo-db:
  mongo-configdb:
  redis-data:
  mysql-data:
