version: '3.1'
networks:
  api-db:
    driver: bridge
services:
  mongo-moka:
    build: mongodb
    container_name: mongo-moka
    hostname: mongo-moka
    networks:
      - api-db
    ports:
      - 27017:27017
    volumes:
      - 'mongo-db:/data/db'
      # - './mongodb/db:/data/db'
      # - './mongodb/configdb:/data/configdb'
      # - './mongodb/log:/data/log'

  redis-moka:
    build: redis
    container_name: redis-moka
    hostname: redis-moka
    networks:
      - api-db
    ports:
      - 6379:6379
    volumes:
      - './redis/data:/data'

  mysql-moka:
    build: mysql
    container_name: mysql-moka
    hostname: mysql-moka
    networks:
      - api-db
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    volumes:
      - './mysql/data:/var/lib/mysql'
    ports:
      - '3306:3306'

volumes:
  mongo-db:
# mongo-configdb:
# redis-data:
# mysql-data:
