version: '3.1'
services:
  mongo-moka:
    build: mongodb
    ports:
      - 27017:27017
    volumes:
      - 'mongo-db:/data/db'
      - 'mongo-configdb:/data/configdb'

  redis-moka:
    build: redis
    ports:
      - 6379:6379
    volumes:
      - 'redis-data:/data'

  mysql-moka:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - '3306:3306'

volumes:
  mongo-db:
  mongo-configdb:
  redis-data:
  mysql-data:
