version: '3.1'
services:
  web-moka:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    external_links:
      - mongo-moka:mongo-moka
      - redis-moka:redis-moka
      - mysql-moka:mysql-moka
